### ISSUE TITLE
Lenovo İdeapad Z500 Not Working

### ISSUE THREAD

**Issue by ilhanaydinli** [alexluckett/LenovoFanControl#1]
Hello there,
When I run fileWriter.py I get an error like below how can I fix it? I guess this is why the fan control does not work.

`$ sudo ./fileWriter.py 
Auto detected file_mode path:/sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/fan_mode
Traceback (most recent call last):
  File "./fileWriter.py", line 46, in <module>
    raise ArgumentError('No second argument to use as fan mode')
TypeError: __init__() takes exactly 3 arguments (2 given)
`

**Comment by alexluckett** [comment]
Hey! Sorry for the very late reply... haven't checked things for a while.

​Run ​fanControl.py directly​ instead​. That should launch the AppIndicator
and provide an an interface for you to set the fan mode. fileWriter.py
wasn't meant for end users.

E.g. as a startup script:
$ ./fanControl.py &

**Comment by alexluckett** [comment]
Hey @ilhanaydinli, is this something you still need support with?
